use regex::Regex;
use std::{
    fs,
    path::{Path, PathBuf},
};

const GENERATED_HEADER: &str = "\
// This file is generated by the codegen crate. Do not edit it manually.

use serde::{Deserialize, Serialize};

";

#[derive(Debug, PartialEq)]
struct KotlinFile {
    package: String,
    declaration: KotlinDeclaration,
}

#[derive(Debug, PartialEq)]
enum KotlinDeclaration {
    DataClass {
        name: String,
        properties: Vec<KotlinProperty>,
    },
    Enum {
        name: String,
        variants: Vec<String>,
    },
}

#[derive(Debug, PartialEq)]
struct KotlinProperty {
    name: String,
    kotlin_type: String,
}

pub fn generate(input_dir: &Path, output_file: &Path) -> Result<usize, String> {
    let mut source_files = Vec::new();
    collect_kotlin_files(input_dir, &mut source_files)?;
    source_files.sort();

    let mut declarations = Vec::new();
    for source_file in source_files {
        let class_name = source_file
            .file_stem()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("Invalid Kotlin file name: {}", source_file.display()))?;

        if !has_supported_suffix(class_name) {
            continue;
        }

        let source = fs::read_to_string(&source_file)
            .map_err(|error| format!("Unable to read {}: {error}", source_file.display()))?;
        let parsed = parse_kotlin_file(&source)
            .map_err(|error| format!("Unable to parse {}: {error}", source_file.display()))?;

        if declaration_name(&parsed.declaration) != class_name {
            return Err(format!(
                "Declaration name {} does not match file name {class_name} in {}",
                declaration_name(&parsed.declaration),
                source_file.display()
            ));
        }

        declarations.push(parsed);
    }

    let generated = render_rust(&declarations)?;
    if let Some(parent) = output_file.parent() {
        fs::create_dir_all(parent)
            .map_err(|error| format!("Unable to create {}: {error}", parent.display()))?;
    }
    fs::write(output_file, generated)
        .map_err(|error| format!("Unable to write {}: {error}", output_file.display()))?;

    Ok(declarations.len())
}

fn collect_kotlin_files(directory: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(directory)
        .map_err(|error| format!("Unable to read {}: {error}", directory.display()))?;

    for entry in entries {
        let path = entry
            .map_err(|error| format!("Unable to read {}: {error}", directory.display()))?
            .path();
        if path.is_dir() {
            collect_kotlin_files(&path, files)?;
        } else if path.extension().and_then(|extension| extension.to_str()) == Some("kt") {
            files.push(path);
        }
    }

    Ok(())
}

fn has_supported_suffix(class_name: &str) -> bool {
    ["Dto", "Request", "Response"]
        .iter()
        .any(|suffix| class_name.ends_with(suffix))
}

fn declaration_name(declaration: &KotlinDeclaration) -> &str {
    match declaration {
        KotlinDeclaration::DataClass { name, .. } | KotlinDeclaration::Enum { name, .. } => name,
    }
}

fn parse_kotlin_file(source: &str) -> Result<KotlinFile, String> {
    let package_regex =
        Regex::new(r"(?m)^\s*package\s+([A-Za-z_][A-Za-z0-9_.]*)\s*$").expect("valid regex");
    let package = package_regex
        .captures(source)
        .and_then(|captures| captures.get(1))
        .map(|value| value.as_str().to_owned())
        .ok_or_else(|| "Missing package declaration".to_owned())?;

    let data_class_regex = Regex::new(r"(?s)\bdata\s+class\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*?)\)")
        .expect("valid regex");
    if let Some(captures) = data_class_regex.captures(source) {
        let name = captures[1].to_owned();
        let properties = parse_properties(&captures[2])?;
        return Ok(KotlinFile {
            package,
            declaration: KotlinDeclaration::DataClass { name, properties },
        });
    }

    let enum_regex = Regex::new(r"(?s)\benum\s+class\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{(.*?)\}")
        .expect("valid regex");
    if let Some(captures) = enum_regex.captures(source) {
        let name = captures[1].to_owned();
        let variants = captures[2]
            .split([',', ';'])
            .map(str::trim)
            .filter(|variant| !variant.is_empty())
            .map(|variant| {
                variant
                    .split_whitespace()
                    .next()
                    .unwrap_or(variant)
                    .to_owned()
            })
            .collect();
        return Ok(KotlinFile {
            package,
            declaration: KotlinDeclaration::Enum { name, variants },
        });
    }

    Err("Expected a data class or enum class".to_owned())
}

fn parse_properties(source: &str) -> Result<Vec<KotlinProperty>, String> {
    split_top_level(source, ',')
        .into_iter()
        .filter(|property| !property.trim().is_empty())
        .map(|property| {
            let property_regex = Regex::new(
                r"(?s)^\s*(?:@[A-Za-z0-9_.]+(?:\([^)]*\))?\s*)*(?:val|var)\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+?)\s*(?:=.+)?$",
            )
            .expect("valid regex");
            let captures = property_regex
                .captures(property)
                .ok_or_else(|| format!("Invalid property declaration: {}", property.trim()))?;
            Ok(KotlinProperty {
                name: captures[1].to_owned(),
                kotlin_type: captures[2].trim().to_owned(),
            })
        })
        .collect()
}

fn split_top_level(source: &str, separator: char) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut depth = 0;

    for (index, character) in source.char_indices() {
        match character {
            '<' | '(' | '[' => depth += 1,
            '>' | ')' | ']' => depth -= 1,
            _ if character == separator && depth == 0 => {
                parts.push(&source[start..index]);
                start = index + character.len_utf8();
            }
            _ => {}
        }
    }
    parts.push(&source[start..]);
    parts
}

fn render_rust(files: &[KotlinFile]) -> Result<String, String> {
    let mut output = String::from(GENERATED_HEADER);

    for file in files {
        output.push_str(&format!("// Kotlin package: {}\n", file.package));
        match &file.declaration {
            KotlinDeclaration::DataClass { name, properties } => {
                output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
                output.push_str("#[serde(rename_all = \"camelCase\")]\n");
                output.push_str(&format!("pub struct {name} {{\n"));
                for property in properties {
                    output.push_str(&format!(
                        "    pub {}: {},\n",
                        rust_field_name(&property.name),
                        kotlin_type_to_rust(&property.kotlin_type)?
                    ));
                }
                output.push_str("}\n\n");
            }
            KotlinDeclaration::Enum { name, variants } => {
                output.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub enum {name} {{\n"));
                for variant in variants {
                    output.push_str(&format!(
                        "    #[serde(rename = \"{variant}\")]\n    {},\n",
                        screaming_snake_to_pascal_case(variant)
                    ));
                }
                output.push_str("}\n\n");
            }
        }
    }

    output.truncate(output.trim_end().len());
    output.push('\n');
    Ok(output)
}

fn kotlin_type_to_rust(kotlin_type: &str) -> Result<String, String> {
    let kotlin_type = kotlin_type.trim();
    if let Some(non_nullable) = kotlin_type.strip_suffix('?') {
        return Ok(format!("Option<{}>", kotlin_type_to_rust(non_nullable)?));
    }

    if let Some((container, inner)) = split_generic_type(kotlin_type) {
        let converted = match container {
            "List" | "MutableList" | "Set" | "MutableSet" => {
                format!("Vec<{}>", kotlin_type_to_rust(inner)?)
            }
            "Map" | "MutableMap" => {
                let arguments = split_top_level(inner, ',');
                if arguments.len() != 2 {
                    return Err(format!("Map requires two type arguments: {kotlin_type}"));
                }
                format!(
                    "std::collections::HashMap<{}, {}>",
                    kotlin_type_to_rust(arguments[0])?,
                    kotlin_type_to_rust(arguments[1])?
                )
            }
            _ => return Err(format!("Unsupported generic Kotlin type: {kotlin_type}")),
        };
        return Ok(converted);
    }

    Ok(match kotlin_type {
        "String" | "Char" => "String",
        "Boolean" => "bool",
        "Byte" => "i8",
        "Short" => "i16",
        "Int" => "i32",
        "Long" => "i64",
        "Float" => "f32",
        "Double" => "f64",
        identifier if is_identifier(identifier) => identifier,
        _ => return Err(format!("Unsupported Kotlin type: {kotlin_type}")),
    }
    .to_owned())
}

fn split_generic_type(kotlin_type: &str) -> Option<(&str, &str)> {
    let open = kotlin_type.find('<')?;
    if !kotlin_type.ends_with('>') {
        return None;
    }
    Some((
        &kotlin_type[..open],
        &kotlin_type[open + 1..kotlin_type.len() - 1],
    ))
}

fn is_identifier(value: &str) -> bool {
    let mut characters = value.chars();
    characters
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic() || character == '_')
        && characters.all(|character| character.is_ascii_alphanumeric() || character == '_')
}

fn to_snake_case(value: &str) -> String {
    let mut result = String::new();
    for character in value.chars() {
        if character.is_ascii_uppercase() {
            if !result.is_empty() {
                result.push('_');
            }
            result.push(character.to_ascii_lowercase());
        } else {
            result.push(character);
        }
    }
    result
}

fn rust_field_name(kotlin_name: &str) -> String {
    let snake_case = to_snake_case(kotlin_name);
    if is_rust_keyword(&snake_case) {
        format!("r#{snake_case}")
    } else {
        snake_case
    }
}

fn is_rust_keyword(value: &str) -> bool {
    matches!(
        value,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "try"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "yield"
    )
}

fn screaming_snake_to_pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            match characters.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string()
                        + &characters.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_data_class() {
        let parsed = parse_kotlin_file(
            r#"
                package example.api

                @Serializable
                data class ExampleResponse(
                    val projectId: String,
                    val items: List<ItemDto>,
                    val result: ItemDto?
                )
            "#,
        )
        .unwrap();

        assert_eq!(
            parsed,
            KotlinFile {
                package: "example.api".to_owned(),
                declaration: KotlinDeclaration::DataClass {
                    name: "ExampleResponse".to_owned(),
                    properties: vec![
                        KotlinProperty {
                            name: "projectId".to_owned(),
                            kotlin_type: "String".to_owned(),
                        },
                        KotlinProperty {
                            name: "items".to_owned(),
                            kotlin_type: "List<ItemDto>".to_owned(),
                        },
                        KotlinProperty {
                            name: "result".to_owned(),
                            kotlin_type: "ItemDto?".to_owned(),
                        },
                    ],
                },
            }
        );
    }

    #[test]
    fn parses_enum() {
        let parsed = parse_kotlin_file(
            r#"
                package example.api

                enum class ItemTypeDto {
                    FIRST_ITEM,
                    SECOND_ITEM
                }
            "#,
        )
        .unwrap();

        assert_eq!(
            parsed.declaration,
            KotlinDeclaration::Enum {
                name: "ItemTypeDto".to_owned(),
                variants: vec!["FIRST_ITEM".to_owned(), "SECOND_ITEM".to_owned()],
            }
        );
    }

    #[test]
    fn converts_types_and_names() {
        assert_eq!(
            kotlin_type_to_rust("List<ItemDto?>?").unwrap(),
            "Option<Vec<Option<ItemDto>>>"
        );
        assert_eq!(
            to_snake_case("finishedAtTimestamp"),
            "finished_at_timestamp"
        );
        assert_eq!(rust_field_name("type"), "r#type");
        assert_eq!(screaming_snake_to_pascal_case("UPDATE_FLOW"), "UpdateFlow");
    }

    #[test]
    fn renders_serde_wire_names() {
        let output = render_rust(&[KotlinFile {
            package: "example.api".to_owned(),
            declaration: KotlinDeclaration::Enum {
                name: "ItemTypeDto".to_owned(),
                variants: vec!["FIRST_ITEM".to_owned()],
            },
        }])
        .unwrap();

        assert!(output.contains("#[serde(rename = \"FIRST_ITEM\")]"));
        assert!(output.contains("FirstItem"));
    }
}
