use crate::model::{RustDeclaration, RustType, TypeReference};
use std::collections::HashMap;

const GENERATED_HEADER: &str =
    "// This file is generated by the codegen crate. Do not edit it manually.\n";

pub fn serialize_rust_types(types: &Vec<RustType>) -> String {
    let mut output = String::from(GENERATED_HEADER);

    output.push_str("use serde::{Deserialize, Serialize};\n");

    for rust_type in types {
        match &rust_type.declaration {
            RustDeclaration::Struct { fields } => {
                output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
                output.push_str("#[serde(rename_all = \"camelCase\")]\n");
                output.push_str(&format!("pub struct {} {{\n", rust_type.name));

                for field in fields {
                    let field_name = format_field_name(&field.name);
                    let field_type = format_type_name(&field.type_reference);
                    output.push_str(&format!("    pub {}: {},\n", field_name, field_type));
                }

                output.push_str("}\n");
            }

            RustDeclaration::Enum { cases } => {
                output.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub enum {} {{\n", rust_type.name));
                for case in cases {
                    output.push_str(&format!(
                        "    #[serde(rename = \"{case}\")]\n    {},\n",
                        screaming_snake_to_pascal_case(case)
                    ));
                }

                output.push_str("}\n");
            }
        }
    }

    output.truncate(output.trim_end().len());

    output
}

pub fn serialize_lib_rs(namespace_to_types_map: &HashMap<String, Vec<RustType>>) -> String {
    let mut output = String::new();

    for (namespace, types) in namespace_to_types_map {
        let type_names = types
            .iter()
            .map(|t| t.name.to_string())
            .collect::<Vec<_>>()
            .join(", ");

        output.push_str(&format!("pub mod {};\n", &namespace));
        output.push_str(&format!("pub use {}::{{{}}};\n", &namespace, type_names));
    }

    output
}

fn format_field_name(name: &str) -> String {
    if name == "type" {
        name.replace("type", "r#type")
    } else {
        name.to_string()
    }
}

fn format_type_name(type_reference: &TypeReference) -> String {
    let type_name = if type_reference.parameter_names.is_empty() {
        type_reference.name.to_string()
    } else {
        let parameters = type_reference.parameter_names.join(", ");
        format!("{}<{}>", type_reference.name, parameters)
    };

    if type_reference.nullable {
        format!("Option<{}>", type_name)
    } else {
        type_name
    }
}

fn screaming_snake_to_pascal_case(value: &str) -> String {
    value
        .split('_')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut characters = part.chars();
            match characters.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string()
                        + &characters.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect()
}
