// This file is generated by the codegen crate. Do not edit it manually.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserItemDto {
    pub id: String,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncResultDto {
    pub is_success: bool,
    pub started_at: String,
    pub started_at_timestamp: i64,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub processed_items: Vec<crate::ProcessedSyncItemDto>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunItemDto {
    pub id: String,
    pub flow_id: String,
    pub user_id: String,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub app_version_name: String,
    pub app_version_code: String,
    pub is_expired: bool,
    pub result: String,
    pub report_base64_content: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProcessedSyncItemDto {
    pub path: String,
    pub entity_id: Option<String>,
    pub r#type: crate::ProcessedSyncItemTypeDto,
    pub is_success: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Sha256HashDto {
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunsItemDto {
    pub id: String,
    pub flow_id: String,
    pub user_id: String,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub app_version_name: String,
    pub app_version_code: String,
    pub is_expired: bool,
    pub result: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntityReferenceDto {
    pub path: Option<String>,
    pub group_id: Option<String>,
    pub project_id: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupItemDto {
    pub id: String,
    pub parent_id: Option<String>,
    pub project_id: String,
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorMessageDto {
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowItemDto {
    pub id: String,
    pub project_id: String,
    pub group_id: Option<String>,
    pub name: String,
    pub base64_content: String,
    pub content_hash: crate::Sha256HashDto,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectsItemDto {
    pub id: String,
    pub root_group_id: String,
    pub package_name: String,
    pub name: String,
    pub description: Option<String>,
    pub download_url: String,
    pub image_url: Option<String>,
    pub site_url: Option<String>,
    pub repository_url: Option<String>,
    pub last_sync_result: Option<crate::SyncResultDto>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProcessedSyncItemTypeDto {
    #[serde(rename = "INSERT_GROUP")]
    InsertGroup,
    #[serde(rename = "INSERT_FLOW")]
    InsertFlow,
    #[serde(rename = "UPDATE_FLOW")]
    UpdateFlow,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowsItemDto {
    pub id: String,
    pub project_id: String,
    pub group_id: String,
    pub name: String,
    pub content_hash: crate::Sha256HashDto,
}