// This file is generated by the codegen crate. Do not edit it manually.

use serde::{Deserialize, Serialize};

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EntityReferenceDto {
    pub path: Option<String>,
    pub group_id: Option<String>,
    pub project_id: Option<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ErrorMessageDto {
    pub message: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowItemDto {
    pub id: String,
    pub project_id: String,
    pub group_id: Option<String>,
    pub name: String,
    pub base64_content: String,
    pub content_hash: Sha256HashDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunItemDto {
    pub id: String,
    pub flow_id: String,
    pub user_id: String,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub app_version_name: String,
    pub app_version_code: String,
    pub is_expired: bool,
    pub result: String,
    pub report_base64_content: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunsItemDto {
    pub id: String,
    pub flow_id: String,
    pub user_id: String,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub app_version_name: String,
    pub app_version_code: String,
    pub is_expired: bool,
    pub result: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowsItemDto {
    pub id: String,
    pub project_id: String,
    pub group_id: String,
    pub name: String,
    pub content_hash: Sha256HashDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupItemDto {
    pub id: String,
    pub parent_id: Option<String>,
    pub project_id: String,
    pub name: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProcessedSyncItemDto {
    pub path: String,
    pub entity_id: Option<String>,
    pub r#type: ProcessedSyncItemTypeDto,
    pub is_success: bool,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProcessedSyncItemTypeDto {
    #[serde(rename = "INSERT_GROUP")]
    InsertGroup,
    #[serde(rename = "INSERT_FLOW")]
    InsertFlow,
    #[serde(rename = "UPDATE_FLOW")]
    UpdateFlow,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectsItemDto {
    pub id: String,
    pub root_group_id: String,
    pub package_name: String,
    pub name: String,
    pub description: Option<String>,
    pub download_url: String,
    pub image_url: Option<String>,
    pub site_url: Option<String>,
    pub repository_url: Option<String>,
    pub last_sync_result: Option<SyncResultDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Sha256HashDto {
    pub value: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncResultDto {
    pub is_success: bool,
    pub started_at: String,
    pub started_at_timestamp: i64,
    pub finished_at: String,
    pub finished_at_timestamp: i64,
    pub processed_items: Vec<ProcessedSyncItemDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.dto
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UserItemDto {
    pub id: String,
    pub name: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginRequest {
    pub username: String,
    pub password: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowRequest {
    pub parent: EntityReferenceDto,
    pub base64_content: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowRunRequest {
    pub flow_id: String,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub result: String,
    pub app_version_name: String,
    pub app_version_code: String,
    pub report_base64_content: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostGroupRequest {
    pub path: Option<String>,
    pub project_id: Option<String>,
    pub parent_group_id: Option<String>,
    pub name: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostProjectRequest {
    pub package_name: String,
    pub name: String,
    pub description: Option<String>,
    pub download_url: String,
    pub image_url: Option<String>,
    pub site_url: Option<String>,
    pub repository_url: Option<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResetFlowRunsRequest {
    pub project_id: String,
    pub version_name: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignUpRequest {
    pub username: String,
    pub password: String,
    pub email: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateFlowRequest {
    pub parent: Option<EntityReferenceDto>,
    pub base64_content: Option<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.request
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateGroupRequest {
    pub parent: Option<EntityReferenceDto>,
    pub name: Option<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteFlowResponse {
    pub is_success: bool,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DeleteGroupResponse {
    pub is_success: bool,
    pub modified_group_ids: Vec<String>,
    pub modified_flow_ids: Vec<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowResponse {
    pub flow: FlowItemDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunResponse {
    pub flow_run: FlowRunItemDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowRunsResponse {
    pub stats: Vec<FlowRunsItemDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowsResponse {
    pub flows: Vec<FlowsItemDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GetProjectsResponse {
    pub projects: Vec<ProjectsItemDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GroupsResponse {
    pub groups: Vec<GroupItemDto>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginResponse {
    pub token: String,
    pub user: UserItemDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowResponse {
    pub id: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowRunResponse {
    pub id: String,
    pub is_accepted: bool,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostGroupResponse {
    pub id: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostProjectResponse {
    pub id: String,
    pub root_group_id: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RequestProjectSyncResponse {
    pub is_success: bool,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResetFlowRunsResponse {
    pub is_success: bool,
    pub modified_ids: Vec<String>,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignUpResponse {
    pub user_id: String,
    pub token: String,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateFlowResponse {
    pub flow: FlowItemDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateGroupResponse {
    pub group: GroupItemDto,
}

// Kotlin package: com.github.aivanovski.testswithme.web.api.response
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UsersResponse {
    pub users: Vec<UserItemDto>,
}
