// This file is generated by the codegen crate. Do not edit it manually.
use serde::{Deserialize, Serialize};
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostGroupRequest {
    pub path: Option<String>,
    pub project_id: Option<String>,
    pub parent_group_id: Option<String>,
    pub name: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SignUpRequest {
    pub username: String,
    pub password: String,
    pub email: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResetFlowRunsRequest {
    pub project_id: String,
    pub version_name: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowRequest {
    pub parent: crate::EntityReferenceDto,
    pub base64_content: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostProjectRequest {
    pub package_name: String,
    pub name: String,
    pub description: Option<String>,
    pub download_url: String,
    pub image_url: Option<String>,
    pub site_url: Option<String>,
    pub repository_url: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateFlowRequest {
    pub parent: Option<crate::EntityReferenceDto>,
    pub base64_content: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoginRequest {
    pub username: String,
    pub password: String,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateGroupRequest {
    pub parent: Option<crate::EntityReferenceDto>,
    pub name: Option<String>,
}
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PostFlowRunRequest {
    pub flow_id: String,
    pub duration_in_millis: i64,
    pub is_success: bool,
    pub result: String,
    pub app_version_name: String,
    pub app_version_code: String,
    pub report_base64_content: String,
}