addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.10.4")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.1")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.9.11")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
